### PR TITLE
Use proto files from OpenNMS to generate classes

### PR DESCRIPTION
**Pull request by agalue**
To simplify compatibility and maintenance, instead of on having compiled classes that represent the Protobuf objects, I believe it is better to include the `.proto` files from OpenNMS, and generate the classes dynamically using Maven. That way, if something changes in the future, for instance, change Protobuf version or include new attributes on an existing class, any further changes on the server implementation would be easier.

This PR contains all the changes required for this purpose.

On each `.proto` file, I've added the source where the file was copied from OpenNMS, and explained the changes required to allow the gRPC server code to compile.

There were two minor changes on the `.proto` files:

1) Change the Java Package for Sink and RPC. Although, in the future, we might change the server code instead, to minimize the changes on the original `.proto` files.

2) Rename the class `SinkMessage` inside `sink-message.proto` to be `SinkMessageProto`, because `ipc.proto` already has a class with that name. That also required a small change to import `SinkMessageProto` from `SinkMessageProtos` inside `GrpcIpcServer.java`.

I tested the solution on a local environment using Docker, and everything is now working perfectly fine against Horizon 26.

### CODE REVIEW

**Comment by cgorantla** [comment]
Thanks for taking care of this. 
I think it is better to comment out plugin and add the generated source files back in the source.

**Comment by agalue** [comment]
I believe that defeats the purpose of how I envision the changes in this PR. In my opinion, for any GBP/gRPC application, the contract is the `.proto` files, not the generated classes, as those, should be treated as "run-time" dependencies.

For this reason, if you don't mind me asking, what's the goal or the benefits of copying the generated classes to the source code? Or, what do we lose with merging this PR as it is?

Here is how I tried it:
```
FROM maven:3.6-jdk-8 AS builder
WORKDIR /app
RUN git clone https://github.com/OpenNMS/grpc-server.git && \
    cd grpc-server && \
    git checkout -b feature/reuse-proto-files origin/feature/reuse-proto-files && \
    mvn package

FROM openjdk:8-jdk-slim
COPY --from=builder /app/grpc-server/target/grpc-ipc-server.jar /
COPY docker-entrypoint.sh /
ENTRYPOINT [ "/docker-entrypoint.sh" ]
```

That means it just works, regardless if you have `protoc` installed or not, as I've added all the plugins necessary to detect the OS, install the appropriate compiler, and then generate the code for GPB/gRPC.

**Comment by cgorantla** [comment]
My thoughts: Since we are referencing those java files in the source code, it is better to have those references without compiling.  This is useful when you import the code into any IDE or this library is included anywhere.  Even in OpenNMS we are depending on the same maven plugin to generate but it is commented out. https://github.com/OpenNMS/opennms/blob/c00d40fcdf180d8e72a996989de818c44e9828d6/core/ipc/rpc/kafka/pom.xml#L14

So even from consistency point of view w.r.to OpenNMS project, it is better to have the source files in the library instead of depending on compiler to generate.

**Comment by agalue** [comment]
Done. Let me know if there is something else to address before merging.

**Comment by cgorantla** [comment]
Looks good. Just add  copy right header for the source files.

**Comment by agalue** [comment]
Do you mean the generated files that can be overridden in the future if we need to recompile the proto files? If so, is there a way to automatically add those headers?

**Comment by cgorantla** [comment]
I don't know any automated way of doing it. Just add them manually.

**Comment by agalue** [comment]
Done!

I've used this:

```bash
#!/bin/bash
for f in src/main/java/org/opennms/core/ipc/grpc/common/*.java; do
  echo "Updating $f"
  cat headers $f > temp
  mv -f temp $f
done
```

Anything else?

**Review by cgorantla — APPROVED** [review]

**Pull request merged**
